name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo Hello, world!
      - name: Step2
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cat /etc/os-release
  Test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Step_build
        run: echo Hello, world!
      - name: Step_build
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          cat /etc/os-release
